name: Build font and specimen

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Linux dependencies
      run: |
        sudo snap install yq
    - name: Build font
      run: make build
    - name: Regression Test
      uses: m4rc1e/font-browser-tests-action@v0.1.4
      with:
        paths: ./fonts/variable
        fonts_before: 'google-fonts'