name: Build font and specimen

on: [push]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-fonts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Linux dependencies
      run: |
        sudo snap install yq
    - name: Build font
      run: make build
    - uses: actions/upload-artifact@v3
      with:
        name: built-fonts
        path: 'fonts'
  
  screenshot:
    needs:
      - build-fonts
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: built-fonts
          path: 'fonts'
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: m4rc1e/font-browser-tests-action@main
        with:
          paths: ./fonts/variable
          fonts_before: google-fonts